service: know-god-asset-import
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  stage: ${env:ENVIRONMENT}
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-888294ed
    subnetIds:
      - subnet-f2c2dfda # us-east-1a
      - subnet-1508db62 # us-east-1b
      - subnet-3fd94266 # us-east-1c
  stackTags:
    Name: ${env:PROJECT_NAME}-${self:custom.environmentMap.${env:ENVIRONMENT}}
    owner: apps@cru.org
    application: ${env:PROJECT_NAME}
    env: ${self:custom.environmentMap.${env:ENVIRONMENT}}
    managed_by: serverless-framework
    function: lambda
  timeout: 30
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*"
          Resource:
            - { "Fn::Join" : ['', ["arn:aws:s3:::", "${env:S3_BUCKET_NAME}"]] }
            - "arn:aws:s3:::know-god-assets/*"
  layers:
    - arn:aws:lambda:us-east-1:072686360478:layer:node-16_14_2:1
  environment: ${file(env.js)}

functions:
  unzip-assets:
    handler: index.handler
    events:
      - s3:
          bucket: ${env:S3_BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: GodTools/
            - suffix: .zip
          existing: true

package:
  individually: true
  patterns:
    - '!.webpack/**'
    - '!test/**'
    - '!**/*.test.js'
    - '!.deployment/**'

custom:
  environmentMap:
    production: prod
    staging: stage
    development: dev
    lab: lab
